stages:
  - image
  - check

build-image:
  stage: image
  rules:
    - changes:
      - Dockerfile.ci
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: /kaniko/.docker
  script:
    # Auth to GitLab registry
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    # Build and push
    - cat /kaniko/.docker/config.json
    - echo "$CI_REGISTRY_IMAGE:latest"
    - nslookup "$CI_REGISTRY"
    - /kaniko/executor
        --context "$CI_PROJECT_DIR"
        --dockerfile "$CI_PROJECT_DIR/Dockerfile.ci"
        --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
        --destination "$CI_REGISTRY_IMAGE:latest"
        --cache=true

rua_check:
  stage: check
  image: "$CI_REGISTRY_IMAGE:latest"
  script: |
    ./utils/rua_check.sh

fmt:
  stage: check
  image: "$CI_REGISTRY_IMAGE:latest"
  script: |
    ./utils/fmt.sh --check-only
      
